using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Domir.Client.Core.UI;
using Domir.Client.Editor;
using UnityEditor;
using UnityEngine;

namespace Editor
{
    public static class UIMappingGenerator
    {
        private static readonly string[] UIPaths = { $"UI/{UIConfig.Stack}", $"UI/{UIConfig.Static}", $"UI/{UIConfig.System}" };

        [MenuItem("Domir/Generate UI Mapping")]
        public static void GenerateUI()
        {
            var staticId = UIOrder.StaticId;
            var stackId = UIOrder.StackId;
            var systemId = UIOrder.SystemId;

            var staticIdMap = new Dictionary<string, int>();
            var stackIdMap = new Dictionary<string, int>();
            var systemIdMap = new Dictionary<string, int>();

            var staticEntries = new List<string>();
            var stackEntries = new List<string>();
            var systemEntries = new List<string>();

            foreach (var uiPath in UIPaths)
            {
                var fullPath = $"{EditorConfig.ResourcesPath}/{uiPath}";
                if (!Directory.Exists(fullPath))
                {
                    throw new DirectoryNotFoundException(fullPath);
                }

                var prefabFiles = Directory.GetFiles(fullPath, "*.prefab", SearchOption.AllDirectories);
                foreach (var file in prefabFiles)
                {
                    var fileName = Path.GetFileNameWithoutExtension(file);
                    if (!fileName.EndsWith("UI")) continue;

                    string category;
                    int id;
                    string enumName, enumField;

                    if (fileName.EndsWith(UIConfig.StaticUI))
                    {
                        category = UIConfig.Static;
                        enumName = UIConfig.StaticUIId;
                        enumField = fileName.Replace(UIConfig.StaticUI, string.Empty);
                        id = staticId++;
                    }
                    else if (fileName.EndsWith(UIConfig.StackUI))
                    {
                        category = UIConfig.Stack;
                        enumName = UIConfig.StackUIId;
                        enumField = fileName.Replace(UIConfig.StackUI, string.Empty);
                        id = stackId++;
                    }
                    else if (fileName.EndsWith(UIConfig.SystemUI))
                    {
                        category = UIConfig.System;
                        enumName = UIConfig.SystemUIId;
                        enumField = fileName.Replace(UIConfig.SystemUI, string.Empty);
                        id = systemId++;
                    }
                    else continue;

                    var typeName = $"{fileName}Presenter";

                    var relativePath = file.Replace($"{EditorConfig.ResourcesPath}/", string.Empty).Replace(".prefab", string.Empty).Replace("\\", "/");
                    var entry = $"{{ {enumName}.{enumField}, (typeof({typeName}), \"{relativePath}\") }}";

                    switch (category)
                    {
                        case UIConfig.Static:
                            staticIdMap[enumField] = id;
                            staticEntries.Add(entry);
                            break;
                        case UIConfig.Stack:
                            stackIdMap[enumField] = id;
                            stackEntries.Add(entry);
                            break;
                        case UIConfig.System:
                            systemIdMap[enumField] = id;
                            systemEntries.Add(entry);
                            break;
                    }
                }
            }

            var rootPath = $"{EditorConfig.GeneratedPath}";
            if (!Directory.Exists(rootPath))
            {
                Directory.CreateDirectory(rootPath);
            }

            File.WriteAllText($"{rootPath}/{UIConfig.UIIds}.cs", GenerateUIIds(staticIdMap, stackIdMap, systemIdMap));
            File.WriteAllText($"{rootPath}/{UIConfig.UIMapping}.cs", GenerateUIMapping(staticEntries, stackEntries, systemEntries));
            AssetDatabase.Refresh();
            Debug.Log($"✅ Generated <color=#81C784>{UIConfig.UIIds}.cs</color> and <color=#81C784>{UIConfig.UIMapping}.cs</color> successfully.");
        }

        private static string GenerateUIIds(
            Dictionary<string, int> staticUI,
            Dictionary<string, int> stackUI,
            Dictionary<string, int> systemUI)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine(EditorConfig.UsingCore);
            sb.AppendLine();
            sb.AppendLine(EditorConfig.NamespaceGenerated);
            sb.AppendLine("{");
            sb.AppendLine(GenerateBlock(UIConfig.StaticUIId, staticUI));
            sb.AppendLine(GenerateBlock(UIConfig.StackUIId, stackUI));
            sb.Append(GenerateBlock(UIConfig.SystemUIId, systemUI));
            sb.AppendLine("}");
            sb.Append("// </auto-generated>");
            return sb.ToString();
        }

        private static string GenerateBlock(string className, Dictionary<string, int> values)
        {
            if (values.Count == 0) return string.Empty;

            var sb = new StringBuilder();
            sb.AppendLine($"\tpublic static class {className}");
            sb.AppendLine("\t{");
            foreach (var kvp in values.OrderBy(x => x.Value))
                sb.AppendLine($"\t\tpublic static UIId {kvp.Key} = {kvp.Value};");
            sb.AppendLine("\t}");
            return sb.ToString();
        }

        private static string GenerateUIMapping(
            List<string> staticEntries,
            List<string> stackEntries,
            List<string> systemEntries)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine(EditorConfig.UsingSystem);
            sb.AppendLine(EditorConfig.UsingGeneric);
            sb.AppendLine(EditorConfig.UsingCore);
            sb.AppendLine(EditorConfig.UsingContentsStack);
            sb.AppendLine(EditorConfig.UsingContentsStatic);
            sb.AppendLine(EditorConfig.UsingContentsSystem);
            sb.AppendLine();
            sb.AppendLine(EditorConfig.NamespaceGenerated);
            sb.AppendLine("{");
            sb.AppendLine($"\tpublic static class {UIConfig.UIMapping}");
            sb.AppendLine("\t{");
            sb.AppendLine("\t\tpublic static readonly Dictionary<UIId, (Type type, string prefabPath)> UI = new()");
            sb.AppendLine("\t\t{");

            if (staticEntries.Count > 0)
            {
                sb.AppendLine($"\t\t\t// {UIConfig.Static}");
                foreach (var entry in staticEntries.OrderBy(x => x))
                    sb.AppendLine($"\t\t\t{entry},");
            }

            if (stackEntries.Count > 0)
            {
                sb.AppendLine($"\t\t\t// {UIConfig.Stack}");
                foreach (var entry in stackEntries.OrderBy(x => x))
                    sb.AppendLine($"\t\t\t{entry},");
            }

            if (systemEntries.Count > 0)
            {
                sb.AppendLine($"\t\t\t// {UIConfig.System}");
                foreach (var entry in systemEntries.OrderBy(x => x))
                    sb.AppendLine($"\t\t\t{entry},");
            }

            sb.AppendLine("\t\t};");
            sb.AppendLine("\t}");
            sb.AppendLine("}");
            sb.Append("// </auto-generated>");
            return sb.ToString();
        }
    }
}